[package]
name = "rust-bank"
version = "0.1.0"
edition = "2021"

[dependencies]
duckdb = { version = "1.1.1", features = ["bundled"] }
uuid = {version = "1.11.0", features = ["v4","fast-rng","macro-diagnostics"]}
